services:
  - type: web
    name: mi-peerjs-server
    env: go
    plan: free
    buildCommand: go build -o server main.go
    startCommand: ./server
    envVars:
      - key: GO_VERSION
        value: 1.24.4
